### ISSUE TITLE
Full path

### ISSUE THREAD

**Issue by bmonteiro** [TykTechnologies/tyk-bank#2]
@sedkis, 

Few things not running so well on MacOS all commands with docker-compose exec keycloak keycloak/bin/... need to have the full path after keycloak like this /opt/jboss/keycloak/bin/...
(setup_bank.sh)

**Comment by sedkis** [comment]
Aha.. 

let me check :)

**Comment by bmonteiro** [comment]
All the rest works like a Swiss clock :)

**Comment by sedkis** [comment]
Can you please have a look at #6 @bmonteiro, it patches this. 

Also, can you please explain why full path is necessary instead of relative 

`/opt/jboss/...` instead of `./...`
they both work properly.  is it a best practice thing?
